name: flavorbert_env
channels:
  - pytorch
  - huggingface
  - rdkit
  - conda-forge
dependencies:
  - absl-py
  # - cudatoolkit
  - ipython
  - jupyterlab
  - matplotlib
  - numpy
  - nlp
  - optuna
  - pandas
  - pip
  - pre_commit
  - python=3.8
  - pytorch
  - rdkit
  - regex
  - s3fs
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
  - tqdm
  - transformers
  - wandb
  - pip:
    - accelerate>=0.20.1
    - datasets
    - evaluate
    - transformers>=4.40.0
    - deepchem>=2.4.0rc1.dev20200916050731
    - simpletransformers
    - tensorflow>=2.0
  
